### ISSUE TITLE
Code review for Half way checkpoint

### ISSUE THREAD

**Issue by hbheesetti** [CMPUT301F21T25/AgileSprinters#45]
1. Change the  names so that they all follow a convention
2. Remove any repetition
3. Database class
4. String.xml
5. Install flutter on android studio so that it formats code upon saving
6. Just about anything that is considered poor code quality

**Comment by Leen-Alzebdeh** [comment]
Files to be edited need to also include xml files, mainly need to extract some strings to strings.xml
